### ISSUE TITLE
[IDEA] Resolution independence for other things as well

### ISSUE THREAD

**Issue by tapir** [CodeNMore/CScreen#2]
Some engines like Godot, automatically gives values like mouse and touch position in the range of target game resolution instead of the real screen resolution. Could that be of use for CScreen?

Maybe there can be a function like CScreen.getInTargetCoords(x, y)?

So that I can do something like `local mousepos = CScreen.getInTargetCoords(love.mouse.getPosition())` and not worry about the actual resolution.

If you're interested I can also try to do it and make a PR.

Let me know. Thanks.

**Comment by CodeNMore** [comment]
Sorry for the late response...I like that idea, it would make CScreen much more complete. I'll take a look at your PRs.
